# Generated by Django 4.1.3 on 2022-12-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_mobile_code_and_more'),
        ('client', '0002_mobilecode_tag_remove_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.attribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tag',
        ),
        migrations.DeleteModel(
            name='MobileCode',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='client',
            name='attribute_values',
            field=models.ManyToManyField(to='client.attributevalue'),
        ),
    ]
