# Generated by Django 4.1.3 on 2022-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_attribute_attributevalue_remove_client_mobile_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_code',
            field=models.ManyToManyField(to='client.mobilecode'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(to='client.tag'),
        ),
    ]
