# Generated by Django 4.1.3 on 2022-12-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_mobilecode_tag_remove_client_attribute_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
