# Generated by Django 4.1.3 on 2022-12-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_attribute_values_and_more'),
        ('client', '0005_remove_attributevalue_attribute_delete_attribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
