# Generated by Django 4.1.3 on 2022-12-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_delete_attributevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mobile_code',
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.mobilecode'),
            preserve_default=False,
        ),
    ]
