# Generated by Django 4.1.3 on 2022-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_mobilecode_tag_remove_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('mobile_code', models.ManyToManyField(to='client.mobilecode')),
                ('tag', models.ManyToManyField(to='client.tag')),
            ],
        ),
    ]
