# Generated by Django 4.1.3 on 2022-12-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='mobile_code',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tag',
        ),
    ]
