# Generated by Django 4.1.3 on 2022-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_attribute_attributevalue_remove_client_mobile_code_and_more'),
        ('notification', '0002_remove_notification_mobile_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attribute_values',
            field=models.ManyToManyField(to='client.attributevalue'),
        ),
    ]
