# Generated by Django 4.1.3 on 2022-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_attributevalue_attribute_delete_attribute'),
        ('notification', '0003_notification_attribute_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='notification',
            name='mobile_code',
            field=models.ManyToManyField(to='client.mobilecode'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.ManyToManyField(to='client.tag'),
        ),
    ]
