# Generated by Django 4.1.3 on 2022-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_attribute_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
