# Generated by Django 4.1.3 on 2022-12-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('client', '0002_mobilecode_tag_remove_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('message_status', models.CharField(choices=[('SUCCESSFULL', 'SUCCESSFULL'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
        ),
    ]
